#!/bin/bash
# Server performance stats

clear

echo '##############################'
echo '#Total CPU Usage Currently is#'
echo '##############################'
mpstat
echo

echo '####################'
echo '#Total Memory Usage#'
echo '####################'
free -h
echo

echo '##########################'
echo '#Total free disk space is#'
echo '##########################'
df -h | awk '{print $1,$4,$5}'
echo

echo '##############################################'
echo '#Top 5 process withrespect to CPU utilisation#'
echo '##############################################'
ps aux --sort=%cpu | head -n 6 | awk '{print $1 "\t" $2 "\t" $3 "\t" $11}'
echo

echo '#################################'
echo '#Top 5 processes by memory usage#'
echo '#################################'
ps aux --sort=%mem | head -n 6 | awk '{print $1 "\t" $2 "\t" $4 "\t" $11}'
